# Generated by Django 4.1.13 on 2025-04-22 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_alter_customer_options_remove_customer_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='business_billboard',
            new_name='trading_license',
        ),
    ]
