# Generated by Django 4.1.13 on 2025-04-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_rename_business_billboard_customer_trading_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='trading_license',
            field=models.ImageField(blank=True, null=True, upload_to='photos/license/'),
        ),
    ]
