# Generated by Django 4.1.13 on 2025-04-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_userrole_alter_customer_trading_license_and_more'),
    ]

    operations = [
    ]
