# Generated by Django 4.1.13 on 2025-04-23 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_employee_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='address',
            new_name='is_verified',
        ),
    ]
