# Generated by Django 4.1.13 on 2025-04-24 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_alter_employee_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('districts', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='deliverynote',
            options={},
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='customer_remarks',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='estimate_number',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='sales_agent',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='signed_document',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='ageing',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='authorized_signatory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='customer_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer Contact'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='customer_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer Location'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='dates_of_goods_received',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Goods received Goods'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='days_outstanding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='delivery_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='estimate_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='made_on',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='particulars',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='receiver_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='receiver contact'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='receiver name'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='s_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='salesperson',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='transaction_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='uploaded_form',
            field=models.FileField(blank=True, null=True, upload_to='scanned_notes/'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='warehouse',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer Name'),
        ),
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salespersons', to=settings.AUTH_USER_MODEL, verbose_name='SalesPerson')),
            ],
        ),
    ]
